// EdFi.Buzz.UI.Angular/src/app/AdminSurveyReact/adminSurvey.tsx
import * as React from 'react';
import { FunctionComponent, useState } from 'react';
import $ from 'jquery'

import { ApiService } from 'src/app/Services/api.service';
import { SurveyStatus } from '../Models/survey';

export interface AdminSurveyComponentProps {
  api: ApiService;
}

export const AdminSurvey: FunctionComponent<AdminSurveyComponentProps> = (props: AdminSurveyComponentProps) => {
  const [surveyFilteredList, setsurveyFilteredList] = useState([] as SurveyStatus[]);
  const [surveyList, setsurveyList] = useState([] as SurveyStatus[]);
  const [surveyToDelete, setsurveyToDelete] = useState(null as number);
  const [searchText, setsearchText] = useState(null as string);
  const surveyFilterRef = React.createRef<HTMLInputElement>();
  
  if (!surveyFilteredList || surveyFilteredList.length === 0) {
    props.api.survey.getSurveyStatus(
      props.api.authentication.currentUserValue.teacher.staffkey, null)
        .then((surveysValue) => {
          setsurveyList(surveysValue);
          setsurveyFilteredList(surveysValue);
    });
  }
  
  function handleChange() {
    setsearchText(surveyFilterRef.current.value);
    const upperSearchText = searchText.toUpperCase();
    let filteredList = surveyList
      .filter(s => (s.resultSummaryObj.survey.title as string).toUpperCase().includes(upperSearchText));
    setsurveyFilteredList(filteredList);
  }

  function setSurveyToDelete(surveyKey: number) {
    setsurveyToDelete(surveyKey);
  }

  function deleteSurvey() {
    $('#deletesurveyconfirmation').modal('hide');
    if (surveyToDelete) {
        props.api.survey
      .deleteSurvey(props.api.authentication.currentUserValue.teacher.staffkey, surveyToDelete)
      .then(() => {
        const idx = surveyList.findIndex(el => el.surveykey === surveyToDelete);
        if (idx > -1) {
          surveyList.splice(idx, 1);
        }
        if (searchText) {
          const textIndex = surveyFilteredList.findIndex(el => el.surveykey === surveyToDelete);
          if (textIndex > -1) {
            surveyFilteredList.splice(textIndex, 1);
          }
        }
        setsurveyToDelete(null);
      });
    }
  }

  return (
    <>
    <div className="container">
      <div className="position-relative p-t-10">
        <a className="btn-outline-nav inline-block position-relative" style={{ 'top':'-10px', 'left':'0px'}} href="javascript:history.back(-1)">
          <i className="ion ion-md-arrow-dropleft f-s-37 position-absolute" style={{ 'top': '-1px', 'left': '10px' }}></i>
        </a>
        <h1 className="inline-block position-absolute" style={{'top':'3px', 'left':'44px'}}>Administrate <span>surveys</span></h1>
      </div>
      
      <div className="row">
        <div className="col-12">
          <div className="card">
            <div className="card-body d-flex form-group" style={{'marginBottom': '0'}}>
              <div className="input-group">
                <input onChange={handleChange} ref={surveyFilterRef} type="text" className="form-control" id="searchInputs" placeholder="Search"/>
                <div className="input-group-append">
                  <button className="btn btn-primary" type="button" onClick={handleChange}>
                    <label>Search</label>
                      <i className="ion ion-md-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        
      {(!surveyFilteredList) &&
      <div className="row">
        <div className="col-12">
          <div className="alert alert-warning">
            No survey found.
          </div>
        </div>
      </div>
      }

      {(surveyFilteredList) &&
      <div className="row">
        {surveyFilteredList.map((survey, index) => {
          return <div className="col-12 col-md-6" key={survey.surveystatuskey}>
            <div className="card survey-metadata">
                <div className="card-body">
                  <div>
                    <h2>{survey.resultSummaryObj.survey.title}</h2>
                    <p><span>Survey Key:</span> {survey.surveystatuskey} </p>
                    <p><span>Job Status:</span> {survey.jobstatus.description} </p>
                    <p><span>Questions:</span> {survey.resultSummaryObj.survey.questions} </p>
                    <p><span>Answers Load:</span> {survey.resultSummaryObj.process.load} </p>
                    <p><span>Answers Rejected:</span> {survey.resultSummaryObj.process.rejected} </p>
                    <p><span>Answers Already Loaded:</span> {survey.resultSummaryObj.process.alreadyLoaded} </p>
                  </div>
                </div>
                <div className="row">
                  <div className="col-2 offset-8">
                    <span onClick={(e) => setSurveyToDelete(survey.surveykey)} className="btn btn-danger btn-delete-note ion-md-trash" data-toggle="modal" data-target="#deletesurveyconfirmation"></span>
                  </div>
                  <div className="col-2">
                    <a className="btn btn-primary ion-md-create"></a>
                  </div>
                </div>
            </div>
          </div>;
          })
        }
      </div>
      }
    </div>

    {/* Modal */}
    <div className="modal" id="deletesurveyconfirmation" data-backdrop="static" data-keyboard="false" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div className="modal-dialog modal-dialog-centered">
        <div className="modal-content">
          <div className="modal-header">
            <h5 className="modal-title" id="deletenoteconfirmationLabel">Buzz Survey Administration</h5>
            <button type="button" className="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div className="modal-body">
            Are you sure you want to delete this survey?
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" data-dismiss="modal">No</button>
            <button type="button" onClick={deleteSurvey} className="btn btn-danger">Yes</button>
          </div>
        </div>
      </div>
    </div>
    </>
  );
};

// EdFi.Buzz.UI.Angular/src/app/AdminSurvey/adminSurvey.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../Services/api.service';
import { Title } from '@angular/platform-browser';
import { SurveyStatus } from '../Models/survey';
declare var $: any;

@Component({
  selector: 'app-admin-survey',
  templateUrl: './adminSurvey.component.html',
  styleUrls: ['./adminSurvey.component.css']
})
export class AdminSurveyComponent implements OnInit {
  private surveyList: SurveyStatus[];
  private surveyFilteredList: SurveyStatus[];
  searchText: string;
  surveyToDelete: number;

  colorList: string[] = ['#03a9f4', '#4361ee', '#3a0ca3', '#7209b7', '#f72585', '#4cc9f0'];

  constructor(
    private api: ApiService,
    private title: Title,
  ) {

    this.title.setTitle('Buzz Administrate Surveys');
  }

  async ngOnInit() {
    this.surveyList = await this.api.survey.getSurveyStatus(
      this.api.authentication.currentUserValue.teacher.staffkey, null);
    this.surveyFilteredList = this.surveyList;
  }

  search() {
    const upperSearchText = this.searchText.toUpperCase();
    this.surveyFilteredList = this.surveyList
      .filter(s => (s.resultSummaryObj.survey.title as string).toUpperCase().includes(upperSearchText));
  }
  
  deleteSurvey() {
    $('#deletesurveyconfirmation').modal('hide');
    if (this.surveyToDelete) {
    this.api.survey
      .deleteSurvey(this.api.authentication.currentUserValue.teacher.staffkey, this.surveyToDelete)
      .then(() => {
        const idx = this.surveyList.findIndex(el => el.surveykey === this.surveyToDelete);
        if (idx > -1) {
          this.surveyList.splice(idx, 1);
        }
        if (this.searchText) {
          const idx = this.surveyFilteredList.findIndex(el => el.surveykey === this.surveyToDelete);
          if (idx > -1) {
            this.surveyFilteredList.splice(idx, 1);
          }
        }
        this.surveyToDelete = null;
      });
    }
  }

  setSurveyToDelete(surveyKey: number) {
    this.surveyToDelete = surveyKey;
  }
}

<div class="container">
  <div class="position-relative p-t-10">
    <a class="btn-outline-nav inline-block position-relative" style="top:-10px; left:0px;"
      href="javascript:history.back(-1)">
      <i class="ion ion-md-arrow-dropleft f-s-37 position-absolute" style="top:-1px; left:10px;"></i>
    </a>
    <h1 class="inline-block position-absolute" style="top:3px; left:44px;">Administrate <span>surveys</span></h1>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body d-flex form-group" style="margin-bottom: 0;">
          <div class="input-group">
            <input [(ngModel)]="searchText" (keyup)="search()" type="text" class="form-control" id="searchInputs"
              placeholder="Search">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button" (click)="search()"><label>Search</label><i
                  class="ion ion-md-search"></i></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="row" *ngIf="!surveyFilteredList ||  surveyFilteredList.length === 0">
    <div class="col-12">
      <div class="alert alert-warning">
        No survey found.
      </div>
    </div>
  </div>

  <div class="row" *ngIf="surveyFilteredList && surveyFilteredList.length > 0">

    <div *ngFor="let survey of surveyFilteredList; let i = index " class="col-12 col-md-6">
      <div class="card survey-metadata">
        <div class="card-body">
          <div [ngStyle]="{'borderLeftColor': colorList[i % 6]}">
            <h2>{{survey.resultSummaryObj.survey.title}}</h2>
            <p><span>Survey Key:</span> {{survey.surveykey}} </p>
            <p><span>Job Status:</span> {{survey.jobstatus.description}} </p>
            <p><span>Questions:</span> {{survey.resultSummaryObj.survey.questions}} </p>
            <p><span>Answers Load:</span> {{survey.resultSummaryObj.process.load}} </p>
            <p><span>Answers Rejected:</span> {{survey.resultSummaryObj.process.rejected}} </p>
            <p><span>Answers Already Loaded:</span> {{survey.resultSummaryObj.process.alreadyLoaded}} </p>
          </div>
        </div>
        <span (click)="setSurveyToDelete(survey.surveykey)" class="btn btn-danger btn-delete-note ion-md-trash" data-toggle="modal" data-target="#deletesurveyconfirmation"></span>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal" id="deletesurveyconfirmation" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deletenoteconfirmationLabel">Buzz Survey Administration</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this survey?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-danger" (click)="deleteSurvey()">Yes</button>
      </div>
    </div>
  </div>
</div>
