// EdFi.Buzz.UI.Angular/src/app/Features/Landings/TeacherLandingReact/teacherLanding.tsx
import * as React from 'react';
import { FunctionComponent, useEffect, useRef, useState } from 'react';

import './teacherLanding.css';
import { ApiService } from 'src/app/Services/api.service';
import { Student, Section } from 'src/app/Models'

export interface TeacherLandingComponentProps {
  onClick?: () => void;
  api: ApiService;
}

function Search(props) {
  const sectionSelectionRef = React.createRef<HTMLSelectElement>();
  const studentFilterRef = React.createRef<HTMLInputElement>();

  function searchEventHandler(e) {
    const sectionkey = sectionSelectionRef.current.value;
    const studentFilter = studentFilterRef.current.value;
    props.onSearch(sectionkey, studentFilter);
  }

  return <div className="card">
    <div className="card-body" style={{ "padding": "1rem" }}>
      <div className="row">
        <div className="col-12 col-lg-12 form-group" style={{ "marginBottom": 0 }}>
          <label><h4> Filters </h4> </label>
          <div className="input-group">
            <select className="form-control" name="repeatSelect" id="sectionsSelect" ref={sectionSelectionRef} onChange={searchEventHandler}>
              <option value="null">Select a section</option>
              {props.sectionList.map(si => <option value={si.sectionkey} key={si.sectionkey}>{si.sessionname}</option>)}
            </select>
            <input type="text" className="form-control" id="studentNameInputs" placeholder="Student Name" ref={studentFilterRef} onKeyUp={searchEventHandler} />
            <div className="input-group-append">
              <button className="btn btn-primary" type="button" onClick={searchEventHandler}><label>Search</label><i
                className="ion ion-md-search"></i></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>;
}


function StudentCard(props) {
  const student = props.student;
  const [isCollapsed, setIsCollapsed] = useState(false);
  return (<div className="card">
    <div className="card-body p-t-0">

      <div className="d-flex p-t-12">
        <div>
          <a href={`#/app/studentDetail/${student.studentschoolkey}`}>
            <div className="image-container img-avatar img-size">
              <img src={student.pictureurl} alt={`{student.name} Profile Picture`} />
            </div>
          </a>
        </div>
        <div className="flex-grow-1 overflow-hidden">
          <h3 className="m-b-2 d-flex">{student.name}</h3>
          <p className="text-muted m-b-1">{student.studentkey}</p>
          {(student.primaryemailaddress) && <a className="m-b-2 text-ellipsis"
            href="mailto:{{student.primaryemailaddress}}" title="{{student.primaryemailaddress}}">
            {student.primaryemailaddress}
          </a>
          }
          {(!student.primaryemailaddress) && <p className="alert alert-primary">No email</p>}
        </div>
      </div>

      <div className={`${isCollapsed ? 'collapse' : ''}`}>
        {(student.contacts && student.contacts.length > 0) &&
          <span className="text-muted">
            {student.contacts[0].relationshiptostudent}: {student.contacts[0].contactlastname}, {student.contacts[0].contactfirstname}
            <a className="inline-block" href="tel:{{student.contacts[0].phone}}">{student.contacts[0].phonenumber}</a>
          </span>
        }
        {(!student.contacts || student.contacts.length === 0) &&
          <div className="alert alert-primary">Student have no contacts</div>
        }
      </div>


      <div className={`collapse ${isCollapsed ? 'show' : ''}`}>
        <hr />
        <h3>Primary Contact</h3>
        {(student.contacts && student.contacts.length > 0) &&
          <p className="m-l-10">
            <span className="text-muted block">{student.contacts[0].contactlastname}, {student.contacts[0].contactfirstname} ({student.contacts[0].relationshiptostudent})</span>
            <i className="icon ion-md-mail"></i>&nbsp;<a className="m-b-2 "
              href="mailto:{{student.contacts[0].primaryemailaddress}}">{student.contacts[0].primaryemailaddress}</a>
            <br />
            <i className="icon ion-md-phone-portrait"></i>&nbsp;<span className="text-muted"><a
              href="tel:{{student.contacts[0].phonenumber}}">{student.contacts[0].phonenumber}</a></span>
            <span className="text-muted block">{student.contacts[0].streetnumbername} {student.contacts[0].apartmentroomsuitenumber}</span>
          </p>}
        {(!student.contacts || student.contacts.length === 0) &&
          <div className="alert alert-primary">Student have no contacts</div>}

        {(student.contacts && student.contacts.length > 0) &&
          <h4>Preferred Contact Method: <span className="text-muted">{student.contacts[0].preferredcontactmethod}</span></h4> &&
          <h4>Best time to contact: <span className="text-muted">{student.contacts[0].besttimetocontact}</span></h4>}

        <a href={`#/app/studentDetail/${student.studentschoolkey}`}
          className="btn btn-block btn-outline-primary btn-rounded mt-3">Survey Results</a>
        <hr />
        <h3>Notes</h3>
        {(student.contacts && student.contacts.length > 0) &&
          (student.contacts[0].contactnotes || []).map(note =>
            <p className="text-muted m-b-2">{note}</p>)}
      </div>

    </div>

    <div className="card-footer">
      <i onClick={() => setIsCollapsed(!isCollapsed)}
        className={`ion rounded block text-center f-s-28 cursor-pointer ${isCollapsed ? 'ion-md-arrow-dropup-circle' : 'ion-md-arrow-dropdown-circle'}`}
        style={{ "color": "#03a9f4" }}></i>
    </div>
  </div >);
}

export const TeacherLanding: FunctionComponent<TeacherLandingComponentProps> = (props: TeacherLandingComponentProps) => {

  const [sectionList, setSections] = useState([] as Section[]);
  const [studentList, setStudentList] = useState([] as Student[]);

  if (!sectionList || sectionList.length === 0) {
    props.api.section.getByTeacherId().then(sectionsValue => {
      setSections(sectionsValue);
      props.api.student.get(sectionsValue[0].sectionkey).then(studentsValue => setStudentList(studentsValue));
    });
  }


  function onSearchHandle(sectionKey: string, studentFilter: string) {
    props.api.student.get(sectionKey, studentFilter).then(studentsValue => setStudentList(studentsValue));
  }

  return <main role="main" className="container">
    <h1>Home, <span>class roster</span></h1>

    <Search sectionList={sectionList} onSearch={onSearchHandle} />

    {(studentList.length > 0) &&
      <div className="row align-items-center m-b-10">
        <div className="col">
          <div className="d-flex justify-content-between">
            <h2 className="">Students: {studentList.length}</h2>
            <div className="d-flex" >
              <button className="btn btn-primary m-l-10" /*(click)="setView('Grid')"*/><i className="ion ion-md-grid"></i></button>
              <button className="btn btn-primary m-l-10" /*(click)="setView('List')"*/><i className="ion ion-md-list"></i></button>
            </div>
          </div>
        </div>
      </div>}


    <div className="row" >
      {studentList
        .sort((a, b) => a.studentlastname.localeCompare(b.studentlastname))
        .map(si => <div className="col-lg-4" key={si.studentschoolkey}><StudentCard student={si} /></div>)
      }
    </div>

  </main>;
};

// EdFi.Buzz.UI.Angular/src/app/Features/Landings/TeacherLanding/teacherLanding.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../../Services/api.service';
import { Student, Teacher, Section } from 'src/app/Models';

@Component({
  selector: 'app-teacher-landing',
  templateUrl: './teacherLanding.component.html',
  styleUrls: ['./teacherLanding.component.css']
})

export class TeacherLandingComponent implements OnInit {
  students: Student[];
  teacher: Teacher;
  sections: Section[];
  searchByStudentName: string;
  currentSection: string;
  isSurveyResultsVisible: boolean;
  view: string;


  constructor(private api: ApiService) {
    this.students = [];
    this.searchByStudentName = null;
    this.currentSection = null;
    this.isSurveyResultsVisible = false;

    this.view = localStorage['studentListViewType'] || 'Grid';
    // this.view = "List";
  }

  ngOnInit() {
    this.search();
  }

  async search() {
    this.teacher = this.api.authentication.currentUserValue.teacher;
    this.sections = await this.api.section.getByTeacherId();
    this.students = await this.api.student.get(this.currentSection, this.searchByStudentName);
  }

  toggleSurveyResults() {
    this.isSurveyResultsVisible = !this.isSurveyResultsVisible;
  }

  setView(viewType: string) {
    localStorage['studentListViewType'] = viewType;
    this.view = viewType; /* Grid | List */
  }


}

<main role="main" class="container">

  <h1>Home, <span>class roster</span></h1>

  <div class="card">
    <div class="card-body" style="padding: 1rem;">
      <div class="row">
        <div class="col-12 col-lg-12 form-group" style="margin-bottom: 0;">
          <label><h4> Filters </h4> </label>
          <div class="input-group">
            <select class="form-control" name="repeatSelect" id="sectionsSelect" [(ngModel)]="currentSection"
              (change)="search()">
              <option [value]="null">Select a section</option>
              <option *ngFor="let section of sections" [value]="section.sectionkey">{{section.sessionname}} - {{section.schoolyear}}</option>
            </select>
            <input [(ngModel)]="searchByStudentName" type="text" class="form-control" id="studentNameInputs"
              placeholder="Student Name" (keyup)="search()">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button" (click)="search()"><label>Search</label><i
                  class="ion ion-md-search"></i></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row align-items-center m-b-10" ng-if="students.length > 0">
    <div class="col">
      <div class="d-flex justify-content-between">
        <h2 class="">Students: {{students.length}}</h2>
        <div class="d-flex" >
          <button class="btn btn-primary m-l-10" (click)="setView('Grid')"><i class="ion ion-md-grid"></i></button>
          <button class="btn btn-primary m-l-10" (click)="setView('List')"><i class="ion ion-md-list"></i></button>
        </div>
      </div>
    </div>
  </div>

  <div class="row" *ngIf="view=='Grid'">
    <div class="col-lg-4" *ngFor="let student of students">
      <app-student-card [student]="student"></app-student-card>
    </div>
  </div>

  <div class="row" *ngIf="view=='List'">
    <div class="card" style="width: 100%;">
      <div class="card-body table-responsive-md">
        <table class="table table-bordered table-striped verticle-middle">
          <thead>
            <tr>
              <th>Student Name</th>
              <th style="margin-left: 2em;">Student Email</th>
              <th>Primary Contact</th>
              <th> </th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let student of students">
              <td>

                <img [src]="student.pictureUrl" alt="{{student.name}} Profile Picture" class="imgage-round"
                  style="width: 32px;" />
                <a [routerLink]="['/app/studentDetail']" [state]="{studentId: student.studentId}">
                  &nbsp;{{student.name}}
                </a>
                <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;{{student.studentId}}
              </td>
              <td>
                <a href="mailto:{{student.email}}">{{student.email}}</a>
              </td>

              <td>{{student.guardians[0].name}} ({{student.guardians[0].relationship}})<br>
                Preferred Contact Method: {{student.guardians[0].relationship}} <br>
                <a href="tel:{{student.guardians[0].phone}}">{{student.guardians[0].phone}}</a>
              </td>

              <td class="text-center">
                <a class="btn btn-outline-mail table-btn-outline" tooltip-placement="bottom">
                  <i class="ion ion-md-mail"></i>
                  <div class="bubble-counter blue">5</div>
                </a>
                <a class="btn btn-outline-notifications table-btn-outline">
                  <i class="ion ion-md-notifications-outline"></i>
                  <div class="bubble-counter orange">12</div>
                </a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</main>
