// EdFi.Buzz.UI.Angular/src/app/Features/Login/login.component.ts
// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { AuthService, GoogleLoginProvider, SocialUser } from 'angularx-social-login';
import { ApiService } from 'src/app/Services/api.service';
import { Title } from '@angular/platform-browser';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers: [AuthService]
})

export class LoginComponent implements OnInit {

  loading = false;
  returnUrl: string;
  error = '';

  public model = {
    loggedIn: false,
    user: {}
  };

  constructor(
    private socialAuthService: AuthService,
    private api: ApiService,
    private route: ActivatedRoute,
    private router: Router,
    private title: Title
  ) {
    title.setTitle('Buzz Login');
  }

  ngOnInit() {
    this.model.user = null;
    this.socialAuthService.authState.subscribe(async (user) => {
      const returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/';

      console.log('trace this');
      console.log(sessionStorage.getItem('currentUser'));
      console.log(user);

      if (!user) {
        return;
      }

      this.model.user = user;
      this.model.loggedIn = (user != null);

      // Save temp token
      sessionStorage.setItem('validatingToken', user.idToken);

      // authenticationService
      const isUserValid = await this.api.authentication.validateSocialUser(user.email, user.idToken);
      sessionStorage.removeItem('validatingToken');
      if (isUserValid) {
        this.router.navigate([returnUrl]);
      }
    });
  }

  signIn(): void {
    this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID);
  }

  signOut(): void {
    this.socialAuthService.signOut(true).then(result => { localStorage.clear(); });
  }

}

<main role="main" class="container h-100">
  <div class="row justify-content-center h-100">
    <div class="">
      <!--<div class="alert alert-danger"><i class="icon ion-md-information-circle f-s-20"></i> Thank you for helping us during this Pilot. Our team is working very hard every day to bring relevant data to improve your students education. Please let us know if you have any feedback.</div>-->
      <div class="card m-t--50">
        <div class="card-body">
          <div class="text-center">
            <img src="/assets/Owl-Logo-GrandBend.png" style="width: 100%; max-width: 350px;" />

          </div>
          <h1 class=" text-center m-t-25">TOD - Teacher Observation Dashboard</h1>
          <div class="text-center m-t-20">
            <a (click)="signIn()" class="btn btn-primary">SSO Login</a>
            <p class="m-t-30" *ngIf="model.loggedIn">
              Currently logged in as: {{model.user.name}}
              <br />
              <a (click)="signOut();">Logout</a>
            </p>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-between align-items-center">
          <span class="text-left">
            <a ui-sref="app.privacypolicy"><i class="icon ion-md-lock"></i> Privacy Policy</a>
          </span>
          <div class="float-right">0.0.1</div>
        </div>
      </div>
    </div>
  </div>
</main>

// EdFi.Buzz.UI/src/Feature/Login/index.tsx
/*
 * SPDX-License-Identifier: Apache-2.0
 * Licensed to the Ed-Fi Alliance under one or more agreements.
 * The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
 * See the LICENSE and NOTICES files in the project root for more information.
 */
import * as React from 'react';
import { FunctionComponent } from 'react';

import SocialButton from './SocialButton';
import { ADFSButton } from './LoginADFS';

import { ApiService } from '../../Services/ApiService';
import { User } from '../../Services/AuthenticationService';

export interface LoginComponentProps {
  api: ApiService;
  returnUrl?: string;
  navigate: (url: string) => void;
  googleClientId?: string;
  adfsClientId?: string;
  adfsTenantId?: string;
}

export const Login: FunctionComponent<LoginComponentProps> = (props: LoginComponentProps) => {
  document.title = 'EdFi Buzz: Login';

  const model = {
    loggedIn: false,
    user: {} as any
  };
  model.user = null;

  async function onUserAuthState(user: User) {
    const returnUrl = props.returnUrl || '/';

    if (!user) {
      return;
    }

    // authenticationService
    const isUserValid = await props.api.authentication.validateSocialUser(user.email, user.token, user.tokenProvider);
    if (isUserValid) {
      props.navigate(returnUrl);
    }
  }

  const handleSocialLogin = (user: { email: any; token: { idToken: any } }) => {
    const _user: User = {
      email: user.email,
      token: user.token.idToken,
      tokenProvider: 'react-social-login',
      teacher: null
    };
    onUserAuthState(_user);
  };

  const handleSocialLoginFailure = (err: { message: any }) => {
    console.log(err.message);
  };

  return (
    <main role='main' className='container h-100'>
      <div className='row justify-content-center h-100'>
        <div className=''>
          <div className='card m-t--50'>
            <div className='card-body'>
              <div className='text-center'>
                <img src='/assets/Owl-Logo-GrandBend.png' style={{ 'width': '100%', 'maxWidth': '350px' }} alt="District Logo" />

              </div>
              <h1 className=' text-center m-t-25'>Buzz</h1>
              {/* Boolean(0), Boolean(null), Boolean(undefined) returns false  */
                (Boolean(props.googleClientId)) && <div className='text-center m-t-20'>
                  <SocialButton
                    className='btn btn-primary'
                    provider='google'
                    autoLogin={false}
                    appId={props.googleClientId!}
                    onLoginSuccess={handleSocialLogin}
                    onLoginFailure={handleSocialLoginFailure}
                    key={'google'}
                  >
                  Login with Google
                  </SocialButton>
                </div>}
              {(Boolean(props.adfsClientId)) && <div>
                <ADFSButton
                  className='btn btn-primary'
                  clientId={props.adfsClientId!}
                  tenantId={props.adfsTenantId!}
                  onLoggin={(user) => onUserAuthState(user)} >
                    Login with ADFS
                </ADFSButton>
              </div>}
            </div>
            <div className='card-footer d-flex justify-content-between align-items-center'>
              <span className='text-left'>
                <a href='/app.privacypolicy'><i className='icon ion-md-lock'></i> Privacy Policy</a>
              </span>
              <div className='float-right'>0.0.1</div>
            </div>
          </div>
        </div>
      </div>
    </main >

  );
};
