// fixitfriday.ui.angular/src/app/Features/Login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { AuthService, GoogleLoginProvider, SocialUser } from 'angularx-social-login';
import { ApiService } from 'src/app/Services/api.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers: [AuthService]
})

export class LoginComponent implements OnInit {

  loading = false;
  returnUrl: string;
  error = '';

  public model = {
    loggedIn: false,
    user: {}
  };

  constructor(
    private socialAuthService: AuthService,
    private api: ApiService,
    private route: ActivatedRoute,
    private router: Router) { }

  ngOnInit() {
    this.model.user = null;
    this.socialAuthService.authState.subscribe(async (user) => {
      this.returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/';

      console.log('trace this');
      console.log(sessionStorage.getItem('currentUser'));
      console.log(user);

      if (!user) {
        return;
      }

      this.model.user = user;
      this.model.loggedIn = (user != null);

      // Save temp token
      sessionStorage.setItem('validatingToken', user.idToken);

      // authenticationService
      if (await this.api.authentication.validateSocialUser(user)) {
        this.router.navigate([this.returnUrl]);
      }
    });
  }

  signIn(): void {
    this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID);
  }

  signOut(): void {
    this.socialAuthService.signOut(true).then(result => { localStorage.clear(); });
  }

  useMockCredentials() {
    this.returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/';
    const user = {
      provider: 'FixItFrydays',
      id: '1234567890',
      email: 'mockuser@fixitfrydays.com',
      name: 'MockName MockLastName',
      photoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRpq-0XdXy8gXKhQ-XCWMNGvnQglIxBJmMWxg',
      firstName: 'MockName',
      lastName: 'MockLastName',
      authToken: '1234567890987654321',
      idToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJtb2NrdXNlci5maXhpdGZyeWRheXMuY29tIiwiYXVkIjoiZml4aXRmcnlkYXlzIiwiZW1haWwiOiJtb2NrdXNlckBmaXhpdGZyeWRheXMuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNb2NrTmFtZSBNb2NrTGFzdE5hbWUiLCJwaWN0dXJlIjoiaHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM_cT10Ym4lM0FBTmQ5R2NScHEtMFhkWHk4Z1hLaFEtWENXTU5Hdm5RZ2xJeEJKbU1XeGciLCJnaXZlbl9uYW1lIjoiTW9ja05hbWUiLCJmYW1pbHlfbmFtZSI6Ik1vY2tMYXN0TmFtZSIsImxvY2FsZSI6ImVuIiwiaWF0IjoxNTkzNTQ1MTYzLCJleHAiOjI1OTM1NDg3NjMsImp0aSI6ImFhYWFhMGRkMzk0ZTEyOTBkNjhiMTA0YzJmYjE4YjUyMTkxYTcxZmIifQ.vx8CQnuHH_qVIFup37yRRGtp93lFECyr7xKIc5EjEro',
      authorizationCode: ''
    };
    this.api.authentication.validateSocialUser(user);
    this.router.navigate([this.returnUrl]);
  }

}

<main role="main" class="container h-100">
  <div class="row justify-content-center h-100">
    <div class="">
      <!--<div class="alert alert-danger"><i class="icon ion-md-information-circle f-s-20"></i> Thank you for helping us during this Pilot. Our team is working very hard every day to bring relevant data to improve your students education. Please let us know if you have any feedback.</div>-->
      <div class="card m-t--50">
        <div class="card-body">
          <div class="text-center">
            <img src="/assets/Owl-Logo-GrandBend.png" style="width: 100%; max-width: 350px;" />

          </div>
          <h1 class=" text-center m-t-25">TOD - Teacher Observation Dashboard</h1>
          <div class="text-center m-t-20">
            <a (click)="signIn()" class="btn btn-primary">SSO Login</a>
            <br />
            <span class="link-text cursor-pointer" (click)="useMockCredentials()">Use mock credentials</span>
            <p class="m-t-30" *ngIf="model.loggedIn">
              Currently logged in as: {{model.user.name}}
              <br />
              <a (click)="signOut();">Logout</a>
            </p>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-between align-items-center">
          <span class="text-left">
            <a ui-sref="app.privacypolicy"><i class="icon ion-md-lock"></i> Privacy Policy</a>
          </span>
          <!--<div class="dropdown login-feedback-button">
            <a class="btn btn-fill-help"
               id="dropdown"
               data-toggle="dropdown"
               aria-haspopup="true"
               aria-expanded="false"
               tooltip-placement="bottom">
              <i class="ion ion-md-help"></i>
            </a>
          </div>-->
          <div class="float-right">0.0.1</div>
        </div>
      </div>
    </div>
  </div>
</main>

// EdFi.Buzz.UI.Angular/src/app/Features/LoginReact/login.tsx
import * as React from 'react';
import { FunctionComponent, useState } from 'react';
import styled from 'styled-components';

import { ApiService } from 'src/app/Services/api.service';
import { ActivatedRoute, Router } from '@angular/router';

import SocialButton from './SocialButton';
import { Environment } from 'src/app/Models';

export interface LoginComponentProps {
  api: ApiService;
  returnUrl?: string;
  navigate: (command: string) => void;
  googleClientId: string;
}

export const Login: FunctionComponent<LoginComponentProps> = (props: LoginComponentProps) => {

  const model = {
    loggedIn: false,
    user: {} as any
  };
  model.user = null;

  async function onUserAuthState(user) {
    const returnUrl = props.returnUrl || '/';

    if (!user) {
      return;
    }

    model.user = user;
    model.loggedIn = (user != null);

    // Save temp token
    const token = user._token.idToken;
    sessionStorage.setItem('validatingToken', token);

    // authenticationService
    const isUserValid = await props.api.authentication.validateSocialUser(user.email, token);
    sessionStorage.removeItem('validatingToken');
    if (isUserValid) {
      props.navigate(returnUrl);
    }
  }

  const handleSocialLogin = (user) => {
    onUserAuthState(user);
  };

  const handleSocialLoginFailure = (err) => {
    console.log(err.message);
  };

  return (
    <main role='main' className='container h-100'>
      <div className='row justify-content-center h-100'>
        <div className=''>
          <div className='card m-t--50'>
            <div className='card-body'>
              <div className='text-center'>
                <img src='/assets/Owl-Logo-GrandBend.png' style={{ 'width': '100%', 'maxWidth': '350px' }} />

              </div>
              <h1 className=' text-center m-t-25'>Buzz</h1>
              <div className='text-center m-t-20'>
                <SocialButton
                  className='btn btn-primary'
                  provider='google'
                  autoLogin={true}
                  appId={props.googleClientId}
                  onLoginSuccess={handleSocialLogin}
                  onLoginFailure={handleSocialLoginFailure}
                  key={'google'}
                >
                  Login with Google
              </SocialButton>
              </div>
            </div>
            <div className='card-footer d-flex justify-content-between align-items-center'>
              <span className='text-left'>
                <a ui-sref='app.privacypolicy'><i className='icon ion-md-lock'></i> Privacy Policy</a>
              </span>
              <div className='float-right'>0.0.1</div>
            </div>
          </div>
        </div>
      </div>
    </main >

  );
};
