// EdFi.Buzz.UI/src/Feature/UploadSurvey/index.tsx
// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

import * as React from 'react';
import { Fragment, useState, useEffect, FunctionComponent } from 'react';
import SurveyStatus from 'Models/SurveyStatus';
import ApiService from 'Services/ApiService';
import { MainContainer, HeadlineContainer, TitleSpanContainer } from 'buzztheme';
import styled from 'styled-components';
import { useParams } from 'react-router-dom';

export interface UploadSurveyProps {
  api: ApiService;
  surveyKey?: string;
}

interface FileStatus {
  fileName?: string;
  isValid?: boolean;
  status?: string;
  error?: string;
  jobId?: string;
  serverJobStatus?: SurveyStatus;
}

const SurveyUploadNote = styled.div`
hyphens: auto;
margin-bottom: 0;
padding-bottom: 0;
text-align: justify;
`;

const UpdateMessage = styled.h2`
text-align: justify;
hyphens: auto;
`;

const StyledFileInputLabel = styled.label`
  font-style: italic;
  text-align: justify;
  border-width: 2px;
  color: var(--slate-gray);
  overflow: hidden;

  &::after {
    height: auto;
  }
`;

const StyledTextParent = styled.div`
  @media (min-width: 769px) {
    flex: 1;
    display: flex;
    align-self: space-between;
    justify-content: space-between;
    flex-direction: row;
  }

  @media (max-width: 768px) {
    display: block;

    & > .label {
      width: 100%
    }
  }

  margin: 0.5rem 0;
  overflow: hidden;
  border: ${(props) => props.theme.border};
  border-radius: 4px;

  :focus-within {
    outline: none !important;
    border-color: var(--denim) !important;
  }

  & > input {
    height: 100%;
    padding: 10px 10px;
    border: none;
    position: relative;
    box-sizing: border-box;
    min-width: 15rem;
    width: 100%;

    :focus {
      outline: none !important;
      outline-width: 0px;
    }

    ::placeholder,
    ::-webkit-input-placeholder {
      font-style: italic;
    }

    :-moz-placeholder {
      font-style: italic;
    }

    ::-moz-placeholder {
      font-style: italic;
    }

    :-ms-input-placeholder {
      font-style: italic;
    }
  }

  & > .label  {
    margin: 0;
    padding: 10px 10px;
    min-width: max-content;
  }
`;


const OutlineButton = styled.button`

&.outline-button {
  width: 100%;
  justify-content: center;
  align-items: center;
  height: 3em;
  border-color: var(--denim) !important;
  border-style: solid;
  color:  var(--denim);
  font-weight: 600;
  border-radius: 4px;
  cursor: pointer;
  background-color: transparent;
}

&.outline-button:hover {
  color: white;
  background-color: var(--denim) !important;
}
`;

export const UploadSurvey: FunctionComponent<UploadSurveyProps> = (props: UploadSurveyProps) => {
  const {api} = props;
  const params: { surveyKey: string } = useParams();
  const {surveyKey} = params;

  const DEFAULT_UPLOAD_LABEL = 'Choose survey file';
  const SURVEY_STATUS_QUERY_TIME_IN_MS = 5000;
  const {SURVEY_MAX_FILE_SIZE_BYTES} = api.survey;

  const storage = sessionStorage;
  const currentUserStaffKey = api.authentication.currentUserValue.teacher.staffkey;

  const [isTitleValid, setIsTitleValid] = useState(true);
  const [surveyToUpdate, setSurveyToUpdate] = useState(null);
  const [isFileUploading, setIsFileUploading] = useState(false);
  const [surveyName, setSurveyName] = useState('');
  const [fileStatusMessage, setFileStatusMessage] = useState<FileStatus>(null);
  const [jobStatusTimer, setJobStatusTimer] = useState(null);
  const [title, setTitle] = useState('');
  const [uploadFileLabelText, setUploadFileLabelText] = useState(DEFAULT_UPLOAD_LABEL);
  const [fileStatusClassName, setFileStatusClassName] = useState(DEFAULT_UPLOAD_LABEL);
  const [fileUploaded, setFileUploaded] = useState<File>(null);

  document.title = 'EdFi Buzz: Upload Survey';


  const resetFileStatusMessage = () => {
    setFileStatusMessage(
      {
        fileName: '',
        isValid: false,
        status: '',
        error: null,
        jobId: null,
        serverJobStatus: null
      }
    );
  };

  const createFileStatusMessage = React.useCallback ((fileStatus: FileStatus): FileStatus => {
    if (!fileStatus || !fileStatus.fileName) {
      return fileStatusMessage;
    }
    const newFileStatus = fileStatus ? (
      {
        fileName: fileStatus.fileName,
        isValid: fileStatus.isValid,
        status: fileStatus.status,
        error: fileStatus.error,
        jobId: fileStatus.jobId,
        serverJobStatus: fileStatus.serverJobStatus
      }
    ) :
      (
        {
          fileName: '',
          isValid: false,
          status: '',
          error: null,
          jobId: null,
          serverJobStatus: null
        }
      );
    return newFileStatus;
  }, [fileStatusMessage]);

  const saveLastUploadedSurvey = React.useCallback((message: FileStatus) => {
    if (message && message.fileName && message.fileName.length > 0) {
      storage.setItem('lastUploadedSurvey', JSON.stringify(message));
    }
  }, [storage]);

  const GetJobStatus = React.useCallback (async (staffkey: number, jobkey: string, currentFileStatus: FileStatus) => {
    const values = await api.survey.getSurveyStatus(staffkey, jobkey);
    const value = values && values.length > 0 ? values[0] : null;
    const statusMessage = currentFileStatus || fileStatusMessage;
    if (!statusMessage || !(statusMessage && statusMessage.fileName && statusMessage.fileName.length > 0)) {
      /* If message don't have value, don't try to check file status. Probably
      the user selected a new file to upload. */
      return;
    }
    if (value !== null) {
      setFileStatusMessage(createFileStatusMessage({ ...statusMessage, serverJobStatus: value }));
      saveLastUploadedSurvey(fileStatusMessage);
      setJobStatusTimer(null);
      if (value && !api.survey.JOB_STATUS_FINISH_IDS.includes(value.jobstatuskey)) {
        /* Job is not finished */
        setJobStatusTimer(setTimeout(
          () => GetJobStatus(value.staffkey, value.jobkey, statusMessage),
          SURVEY_STATUS_QUERY_TIME_IN_MS));
      }
    } else {
      setFileStatusMessage(createFileStatusMessage(statusMessage));
      setJobStatusTimer(setTimeout(
        () => GetJobStatus(staffkey, jobkey, statusMessage),
        SURVEY_STATUS_QUERY_TIME_IN_MS));
    }
  }, [api.survey, createFileStatusMessage, fileStatusMessage, saveLastUploadedSurvey]);

  const loadLastUploadedSurvey = React.useCallback(() => {
    const message = JSON.parse(storage.getItem('lastUploadedSurvey'));
    if (message && message.serverJobStatus && !api.survey.JOB_STATUS_FINISH_IDS.includes(message.serverJobStatus.jobstatuskey)) {
      setFileStatusMessage(createFileStatusMessage(message));
      GetJobStatus(message.serverJobStatus.staffkey, message.serverJobStatus.jobkey, message);
    } else {
      resetFileStatusMessage();
      return undefined;
    }
    return message;
  }, [GetJobStatus, api.survey.JOB_STATUS_FINISH_IDS, createFileStatusMessage, storage]);

  function SurveyStatusAreEqual(Object1: SurveyStatus, Object2: SurveyStatus): boolean {
    return Object1?.surveykey === Object2?.surveykey &&
      Object1?.jobstatuskey === Object2?.jobstatuskey &&
      Object1?.jobkey === Object2?.jobkey &&
      Object1?.staffkey === Object2?.staffkey;
  }

  const PrepareIfUpdatingSurvey = React.useCallback(async () => {
    if (surveyKey && surveyKey.length > 0) {
      const userSurveyList = await (api.survey.getSurveyStatus(
        api.authentication.currentUserValue.teacher.staffkey, null));
      if (userSurveyList) {
        const surveyStatus = userSurveyList.find(el => el.surveykey === +surveyKey);
        if (!SurveyStatusAreEqual(surveyToUpdate, surveyStatus)) {
          setSurveyToUpdate(surveyStatus);
        }
      }
    }
  }, [api.authentication.currentUserValue.teacher.staffkey, api.survey, surveyKey, surveyToUpdate]);

  useEffect(() => {
    PrepareIfUpdatingSurvey();
  }, [surveyToUpdate, PrepareIfUpdatingSurvey]);

  useEffect(() => {
    loadLastUploadedSurvey();
  }, [loadLastUploadedSurvey]);

  useEffect(() => {
    const jobStatusKey = fileStatusMessage?.serverJobStatus?.jobstatuskey;
    const fileClassName = jobStatusKey === 3
      ? 'alert-success'
      : 'alert-warning';
    setFileStatusClassName(fileClassName);
  }, [fileStatusMessage]);

  const cancelUploadStatusChecking = () => {
    if (jobStatusTimer) {
      clearTimeout(jobStatusTimer);
      setJobStatusTimer(null);
    }
  };

  const CheckFileValid = (file: File): FileStatus => {
    if (!file) {
      return { fileName: '', status: 'ERROR', error: 'No file selected', isValid: false };
    }
    if (file.size > SURVEY_MAX_FILE_SIZE_BYTES) {
      const error = `File size (${(file.size / 1024.0).toFixed(2)} Kb)
      must be less than ${(SURVEY_MAX_FILE_SIZE_BYTES / (1024)).toFixed(2)} Kb`;
      const message = { fileName: file.name, status: 'ERROR', error, isValid: false };
      return message;
    }
    return { fileName: file.name, status: 'VALID', isValid: true };
  };

  const prepareFilesList = (files: FileList) => {
    cancelUploadStatusChecking();
    const file = files[0];
    const status = CheckFileValid(file);
    if (!status.isValid) {
      setFileStatusMessage(createFileStatusMessage(status));
      return;
    }
    resetFileStatusMessage();
    setUploadFileLabelText(file.name);
    setFileUploaded(file);
  };

  const onDragOver = e => {
    const event = e as Event;
    event.stopPropagation();
    event.preventDefault();
  };

  const onFileDropped = files => {
    files.preventDefault();
    prepareFilesList(files.dataTransfer.files);
  };

  const onSelectSurvey = event => {
    prepareFilesList((event.target as HTMLInputElement).files);
  };

  const getFileContentAsBase64 = (file: Blob): Promise<string> => new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onerror = () => {
      reader.abort();
      reject(new DOMException('Problem parsing input file.'));
    };

    reader.onload = () => {
      resolve(btoa(reader.result as string));
    };

    reader.readAsBinaryString(file);
  });

  const resetControl = () => {
    setSurveyName('');
    setIsFileUploading(false);
    setFileUploaded(null);
    setUploadFileLabelText(DEFAULT_UPLOAD_LABEL);
  };

  const submitSurvey = async (e) => {
    e.preventDefault();
    const file = fileUploaded as File;
    const status = CheckFileValid(file);
    if (surveyName.length === 0) {
      setIsTitleValid(false);
      return;
    }
    setIsTitleValid(true);

    if (!status.isValid) {
      setFileStatusMessage(createFileStatusMessage(status));
      return;
    }
    setIsFileUploading(true);
    const content = await getFileContentAsBase64(file);
    try {
      const uploadedFileStatus = await api.survey
        .uploadSurvey(currentUserStaffKey, title, content, surveyToUpdate ? surveyToUpdate.surveykey : null);
      const currentFileStatus = createFileStatusMessage({
        fileName: file.name,
        status: 'ACCEPTED',
        isValid: true,
        serverJobStatus: uploadedFileStatus
      });
      await setFileStatusMessage(currentFileStatus);
      saveLastUploadedSurvey({
        fileName: file.name,
        status: 'ACCEPTED',
        isValid: true,
        serverJobStatus: uploadedFileStatus
      });
      await loadLastUploadedSurvey();
      resetControl();
      if (!api.survey.JOB_STATUS_FINISH_IDS.includes(uploadedFileStatus.jobstatuskey)) {
        /* Job is not finished */
        setJobStatusTimer(setTimeout(
          () => GetJobStatus(uploadedFileStatus.staffkey, uploadedFileStatus.jobkey, currentFileStatus),
          SURVEY_STATUS_QUERY_TIME_IN_MS));
      }
    } catch (ex) {
      setFileStatusMessage(createFileStatusMessage({ fileName: file.name, status: 'ERROR', error: ex, isValid: true }));
      resetControl();
    }
  };

  const onChangeSurveyName = (e) => {
    const newValue = e.target.value;
    setSurveyName(newValue);
    setTitle(newValue);
    setIsTitleValid(newValue.length > 0);
  };

  return (
    <MainContainer role='main' className='container'>
      <HeadlineContainer>
        <TitleSpanContainer>Upload survey</TitleSpanContainer>
      </HeadlineContainer>

      {surveyToUpdate && (
        <div className='row'>
          <div className='col'>
            <div className='card'>
              <div className='card-body'>
                <UpdateMessage>You are updating the &quot;{surveyToUpdate.resultSummaryObj.survey.title}&quot; survey</UpdateMessage>
              </div>
            </div>
          </div>
        </div>
      )
      }

      <div className='row'>
        <div className='col'>
          <form onSubmit={submitSurvey}>

            <div className='text-center'
              onDrop={onFileDropped}
              onDragLeave={ev => ev.preventDefault()}
              onDragEnter={ev => ev.preventDefault()}
              onDragOverCapture={onDragOver} onDragOver={onDragOver}>
              <p className='icon ion-md-cloud-upload f-s-50'></p>
              <h3>Drag and drop file here</h3>
              <h3>or</h3>
              <div className='custom-file'>
                <input type='file' onChange={onSelectSurvey}
                  disabled={isFileUploading}
                  className='custom-file-input'
                  id='inputGroupFile01'
                  accept='text/csv' />
                <StyledFileInputLabel className='custom-file-label'>{uploadFileLabelText}</StyledFileInputLabel>
              </div>
            </div>

            <StyledTextParent>
              <input type='text'
                placeholder='Survey Name'
                onChange={onChangeSurveyName}
                value={surveyName} />
              {(!isTitleValid)
                ? <label className='label alert-danger text-justify'>Survey name is required</label>
                : null}
            </StyledTextParent>

            <div className='form-group'>
              <OutlineButton type='submit' className='outline-button'
              >Upload survey</OutlineButton>
            </div>

            {fileStatusMessage
              && fileStatusMessage.fileName
              && fileStatusMessage.fileName.length > 0
              ?
              <div
                className={`alert ${fileStatusClassName}`}>
                <h3>File Upload <strong>{fileStatusMessage.status}</strong></h3>
                      File: {fileStatusMessage.fileName}<br />
                {fileStatusMessage.serverJobStatus
                  ?
                  <Fragment>
                    <h3>Job is <strong>{fileStatusMessage.serverJobStatus.jobstatus.description}</strong></h3>
                    Job Key: {fileStatusMessage.serverJobStatus.jobkey}<br />
                    {fileStatusMessage.serverJobStatus.resultSummaryObj
                      ?
                      <Fragment>
                        <h3>Job Results</h3>
                        Survey Key:{fileStatusMessage.serverJobStatus.resultSummaryObj.survey.surveykey}<br />
                        Survey Title: {fileStatusMessage.serverJobStatus.resultSummaryObj.survey.title}<br />
                        Questions: {fileStatusMessage.serverJobStatus.resultSummaryObj.survey.questions}<br />

                        Answers Loaded: {fileStatusMessage.serverJobStatus.resultSummaryObj.process.load}<br />
                        Answers Rejected: {fileStatusMessage.serverJobStatus.resultSummaryObj.process.rejected}<br />
                        Answers Already Loaded: {fileStatusMessage.serverJobStatus.resultSummaryObj.process.alreadyLoaded}<br />
                      </Fragment>
                      : null
                    }
                    {(!fileStatusMessage.serverJobStatus.resultSummaryObj && fileStatusMessage.serverJobStatus.resultsummary)
                      ?
                      <div className='alert'>
                        {fileStatusMessage.serverJobStatus.resultsummary}
                      </div>
                      : null
                    }
                  </Fragment>
                  : null
                }
                {fileStatusMessage.error
                  ?
                  <p>{fileStatusMessage.error}</p>
                  : null
                }
              </div>
              : null}

          </form>
        </div>
      </div>

      <div className='row'>
        <div className='col'>
          <SurveyUploadNote>
            <p>One column in the survey results must be the unique student identifier and must be
              called <em>StudentUniqueId</em>. Supports Google Forms and Survey Monkey formatted exports.
              You can also use Qualtrics survey exports by removing the first of the two headers.</p>
          </SurveyUploadNote>
        </div>
      </div>

    </MainContainer >
  );

};

// EdFi.Buzz.UI.Angular/src/app/Features/UploadSurvey/uploadSurvey.component.ts
import { Component, ViewChild, ElementRef, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Title } from '@angular/platform-browser';
import { ApiService } from 'src/app/Services/api.service';
import { SurveyStatus } from 'src/app/Models/survey';
import { Router, NavigationStart, Event, ActivatedRoute } from '@angular/router';

interface FileStatus {
  fileName: string;
  isValid: boolean;
  status: string;
  error?: string;
  jobId?: string;
  serverJobStatus?: SurveyStatus;
}

@Component({
  selector: 'app-upload-survey',
  templateUrl: './uploadSurvey.component.html',
  styleUrls: ['./uploadSurvey.component.css']
})
export class UploadSurveyComponent implements OnInit {
  readonly SURVEY_STATUS_QUERY_TIME_IN_MS = 5000; /* 5 seconts intervals */
  readonly SURVEY_MAX_FILE_SIZE_BYTES: number;
  readonly storage: Storage;

  currentUserStaffKey: number;

  private surveyList: SurveyStatus[];

  /// surveyToUpdate null indicates this is not an update, but a normal survey upload.
  private surveyToUpdate: SurveyStatus = null;
  form: FormGroup;
  @ViewChild('UploadFileInput', { static: false }) uploadFileInput: ElementRef;
  @ViewChild('UploadFileLabel', { static: false }) uploadFileLabel: ElementRef;
  progress = 0;
  isFileSelected = false;
  isFileUploading = false;
  message: FileStatus;

  getJobStatusTimer: number;

  constructor(
    private fb: FormBuilder,
    private api: ApiService,
    private title: Title,
    private router: Router,
    private activatedRoute: ActivatedRoute
  ) {
    this.storage = sessionStorage;
    this.SURVEY_MAX_FILE_SIZE_BYTES = this.api.survey.SURVEY_MAX_FILE_SIZE_BYTES;
    this.currentUserStaffKey = this.api.authentication.currentUserValue.teacher.staffkey;

    this.title.setTitle('Buzz Upload Survey');
    this.form = this.fb.group({
      surveyName: [null, Validators.required],
      file: [null]
    });

    this.router.events.subscribe((event: Event) => {
      if (event instanceof NavigationStart) {
        /* clear if there is a timeout waiting */
        this.cancelUploadStatusChecking();
      }
    });
  }

  private cancelUploadStatusChecking() {
    if (this.getJobStatusTimer) {
      clearTimeout(this.getJobStatusTimer);
      this.getJobStatusTimer = null;
    }
  }

  async ngOnInit() {
    this.message = this.loadLastUploadedSurvey();

    this.surveyList = await this.api.survey.getSurveyStatus(
      this.api.authentication.currentUserValue.teacher.staffkey, null);

    this.activatedRoute.paramMap.subscribe(params => {
      if (params.get('id')) {
        this.surveyToUpdate = this.surveyList.find(el => el.surveykey === +params.get('id'));
      }
    });
  }

  loadLastUploadedSurvey() {
    const message = JSON.parse(this.storage.getItem('lastUploadedSurvey'));
    if (message && message.serverJobStatus && !this.api.survey.JOB_STATUS_FINISH_IDS.includes(message.serverJobStatus.jobstatuskey)) {
      this.GetJobStatus(message.serverJobStatus.staffkey, message.serverJobStatus.jobkey);
    }
    return message;
  }
  saveLastUploadedSurvey(message: FileStatus) {
    this.storage.setItem('lastUploadedSurvey', JSON.stringify(message));
  }

  CheckFileValid(file: File): FileStatus {
    if (!file) {
      return { fileName: '', status: 'ERROR', error: 'No file selected', isValid: false };
    }
    if (file.size > this.SURVEY_MAX_FILE_SIZE_BYTES) {
      const error = `File size (${(file.size / 1024.0).toFixed(2)} Kb) must be less than ${(this.SURVEY_MAX_FILE_SIZE_BYTES / (1024)).toFixed(2)} Kb`;
      const message = { fileName: file.name, status: 'ERROR', error: error, isValid: false };
      return message;
    }
    return { fileName: file.name, status: 'VALID', isValid: true };
  }

  prepareFilesList(files: any) {
    this.cancelUploadStatusChecking();
    const file = files[0];
    const status = this.CheckFileValid(file);
    if (!status.isValid) {
      this.message = status;
      return;
    }
    this.message = null;

    this.uploadFileLabel.nativeElement.textContent = file.name;

    this.form.patchValue({ file: file });
    this.form.get('file').updateValueAndValidity();
    this.isFileSelected = this.form.value != null;
  }

  onFileDropped(files) {
    this.prepareFilesList(files);
  }

  onSelectSurvey(event) {
    this.prepareFilesList((event.target as HTMLInputElement).files);
  }

  async submitSurvey() {
    const file = this.form.value.file as File;
    const status = this.CheckFileValid(file);
    if (!status.isValid) {
      this.message = status;
      return;
    }

    this.isFileUploading = true;
    const title = this.form.controls['surveyName'].value;
    const content = await this.getFileContentAsBase64(file);

    this.api.survey
      .uploadSurvey(this.currentUserStaffKey, title, content, this.surveyToUpdate ? this.surveyToUpdate.surveykey : null)
      .then(value => {
        this.message = {
          fileName: file.name,
          status: 'ACCEPTED',
          isValid: true,
          serverJobStatus: value
        };
        this.resetControls();
        if (!this.api.survey.JOB_STATUS_FINISH_IDS.includes(value.jobstatuskey)) {
          /* Job is not finished */
          this.getJobStatusTimer = window.setTimeout(
            () => this.GetJobStatus(value.staffkey, value.jobkey),
            this.SURVEY_STATUS_QUERY_TIME_IN_MS);
        }
      })
      .catch(reason => {
        this.message = { fileName: file.name, status: 'ERROR', error: reason, isValid: true };
        this.resetControls();
      });
  }

  async GetJobStatus(staffkey: number, jobkey: string) {
    const values = await this.api.survey.getSurveyStatus(staffkey, jobkey);
    const value = values.length > 0 ? values[0] : null;
    if (!this.message) {
      /* If message don't have value, don't try to check file status. Probably
      the user selected a new file to upload. */
      return;
    }
    this.message.serverJobStatus = value;
    this.saveLastUploadedSurvey(this.message);
    this.getJobStatusTimer = null;
    if (value && !this.api.survey.JOB_STATUS_FINISH_IDS.includes(value.jobstatuskey)) {
      /* Job is not finished */
      this.getJobStatusTimer = window.setTimeout(
        () => this.GetJobStatus(value.staffkey, value.jobkey),
        this.SURVEY_STATUS_QUERY_TIME_IN_MS);
    }
  }

  getFileContentAsBase64(file: Blob): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();

      reader.onerror = () => {
        reader.abort();
        reject(new DOMException('Problem parsing input file.'));
      };

      reader.onload = () => {
        resolve(btoa(reader.result as string));
      };

      reader.readAsBinaryString(file);
    });
  }

  private resetControls() {
    this.progress = 0;
    this.isFileSelected = false;
    this.isFileUploading = false;

    this.form.reset();
    this.uploadFileInput.nativeElement.value = '';
    this.uploadFileLabel.nativeElement.innerText = 'Choose survey file';
  }
}

<div class="container">
  <div class="position-relative p-t-10">
    <a class="btn-outline-nav inline-block position-relative" style="top:-10px; left:0px;"
      href="javascript:history.back(-1)">
      <i class="ion ion-md-arrow-dropleft f-s-37 position-absolute" style="top:-1px; left:10px;"></i>
    </a>
    <h1 class="inline-block position-absolute" style="top:3px; left:44px;">Upload <span>survey</span></h1>
  </div>

  <div class="row" *ngIf="surveyToUpdate">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h2>You are currently updating the {{surveyToUpdate.resultSummaryObj.survey.title}} survey</h2>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <form [formGroup]="form" (ngSubmit)="submitSurvey()">

            <div class="container" appDnd (fileDropped)="onFileDropped($event)" class="text-center p-b-10">
              <p class="icon ion-md-cloud-upload f-s-50"></p>
              <h3>Drag and drop file here</h3>
              <h3>or</h3>
              <div class="custom-file">
                <input #UploadFileInput type="file" (change)="onSelectSurvey($event)"
                  [disabled]="isFileUploading ? 'disabled' : null" class="custom-file-input" id="inputGroupFile01"
                  accept="text/csv" required>
                <label #UploadFileLabel class="custom-file-label" for="inputGroupFile01">Choose survey file</label>
              </div>
            </div>

            <div class="form-group">
              <input type="text" class="form-control" placeholder="Survey Name" formControlName="surveyName" value="{{ surveyToUpdate ? surveyToUpdate.resultSummaryObj?.survey?.title : '' }}">
              <label *ngIf="form.get('surveyName').touched && form.get('surveyName').invalid"
                class="label alert-danger text-justify w-100"> * Survey name is required </label>
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block btn-lg"
                [disabled]="form.invalid ? 'disabled' : null">Upload survey</button>
            </div>

            <!-- Progress Bar -->
            <div class="progress form-group" *ngIf="progress > 0">
              <div class="progress-bar progress-bar-striped bg-success" role="progressbar" [style.width.%]="progress">
              </div>
            </div>

            <div *ngIf="message"
              [ngClass]="{
                'alert-warning' : message && message.error || (message.serverJobStatus && message.serverJobStatus.jobstatuskey !== 3),
                'alert-success' : !message || (!message.error && message.serverJobStatus && message.serverJobStatus.jobstatuskey === 3)
              }" class="alert">
              <h3>File Upload <strong>{{message.status}}</strong></h3>
              File: {{message.fileName}}<br>
              <ng-container *ngIf="message.serverJobStatus" >
                <h3>Job is <strong>{{message.serverJobStatus.jobstatus.description}}</strong></h3>
                Job Key: {{message.serverJobStatus.jobkey}}<br>
                <ng-container *ngIf="message.serverJobStatus.resultSummaryObj">
                  <h3>Job Results</h3>
                  Survey Key:{{message.serverJobStatus.resultSummaryObj.survey.surveykey}}<br>
                  Survey Title: {{message.serverJobStatus.resultSummaryObj.survey.title}}<br>
                  Questions: {{message.serverJobStatus.resultSummaryObj.survey.questions}}<br>

                  Answers Loaded: {{message.serverJobStatus.resultSummaryObj.process.load}}<br>
                  Answers Rejected: {{message.serverJobStatus.resultSummaryObj.process.rejected}}<br>
                  Answers Already Loaded: {{message.serverJobStatus.resultSummaryObj.process.alreadyLoaded}}<br>
                </ng-container>
                <div *ngIf="!message.serverJobStatus.resultSummaryObj && message.serverJobStatus.resultsummary" class="alert">
                  {{message.serverJobStatus.resultsummary}}
                </div>
              </ng-container>
              <p *ngIf="message.error">{{message.error}}</p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="card-body alert alert-primary text-justify" lang="en"
        style="hyphens: auto; margin-top: -1rem; padding-bottom: 0;">
        <p>One column in the survey results must be the unique student identifier and must be called "StudentUniqueId".
        </p>

        <p>Supports Google Forms and Survey Monkey formatted exports. You can also use Qualtrics survey exports by
          removing the first of the two headers.</p>
      </div>
    </div>
  </div>


</div>
